name: "Send events to App Insights"

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  send-app-insights-event:
    runs-on: ubuntu-latest

    steps:
      - name: "AppInsights: Begin Do Something"
        uses: syedhassaanahmed/app-insights-event-action@main
        with:
          instrumentation-key: "${{ secrets.APP_INSIGHTS_KEY }}"
          event-name: "begin-do-something"

      - name: "Do something"
        run: sleep 5

      - name: "AppInsights: End Do Something"
        uses: syedhassaanahmed/app-insights-event-action@main
        with:
          instrumentation-key: "${{ secrets.APP_INSIGHTS_KEY }}"
          event-name: "end-do-something"